micronaut:
    application:
        name: micronaut-liquibase
    server:
        port: 8081
datasources:
    default:
        url: 'jdbc:mysql://localhost:8889/micronaut_liquibase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
        username: 'root'
        password: 'root'
        driverClassName: 'com.mysql.cj.jdbc.Driver'
jpa:
    default:
        packages-to-scan:
            - 'com.hhimanshu.persistence.entities'
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: false
liquibase:
    default:
        change-log: classpath:db/liquibase-changelog.xml